In [ ]:
import db_tools

wafer = 7867
run = 1
a = 2.0
b = 2.1
c = 2.2
m = 2.3
n = 2.4
rsqd = 2.5

db_tools.insert_ibe(wafer, run, a, b, c)
db_tools.get_wafer_info(wafer)
display(db_tools.get_wafer_trimdata(wafer))

In [ ]:
import pyodbc 
import pandas as pd

cnxn = pyodbc.connect("Driver={ODBC Driver 17 for SQL Server};"
                      "Server=rdm0sql01;"
                      "Database=MES_af;"
                      "Uid=austin;"
                      "Pwd=Test;")
                      #"Trusted_Connection=yes;")
sql = (
    'SELECT TOP (1000) [StatusID]'
    ',[Status]'
    ',[sortorder]'
    ',[MachineName]'
    ',[Area]'
    ',[Phase]'
    ',[Team]'
    ',[NonCycleTime]'
    ',[WIPStatus]'
    ',[Active]'
    ',[WIPCount]'
    'FROM [MES_af].[dbo].[Status]')

df = pd.read_sql(sql, cnxn)
display(df)

In [ ]:
import pyodbc 
import pandas as pd

cnxn = pyodbc.connect("Driver={ODBC Driver 17 for SQL Server};"
                      "Server=rdm0sql01;"
                      "Database=MES_af;"
                      "Uid=austin;"
                      "Pwd=Test;")
                      #"Trusted_Connection=yes;")
sql = (
    'SELECT TOP (1000) [id]'
    ',[fk_wafer]'
    ',[run]'
    ',[a]'
    ',[b]'
    ',[c]'
    ',[m]'
    ',[n]'
    ',[rsqd]'
    ',[created]'
    ',[updated]'
    'FROM [MES_af].[dbo].[IonTrim]')

df = pd.read_sql(sql, cnxn)
display(df)

In [ ]:
import pyodbc 
import pandas as pd

cnxn = pyodbc.connect("Driver={ODBC Driver 17 for SQL Server};"
                      "Server=rdm0sql01;"
                      "Database=MES_af;"
                      "Uid=austin;"
                      "Pwd=Test;")
                      #"Trusted_Connection=yes;")
cursor = cnxn.cursor()

sql = (
        "SELECT "
        "WaferID, "
        "D8Number, "
        "Frequency "
        "FROM [MES_af].[dbo].[Wafers] "
        "WHERE WaferID = '9999'")


cursor.execute(sql)
for row in cursor.fetchall():
    print(row)

In [ ]:
import pyodbc 
import pandas as pd
from datetime import datetime
from pytz import timezone


cnxn = pyodbc.connect("Driver={ODBC Driver 17 for SQL Server};"
                      "Server=rdm0sql01;"
                      "Database=MES_af;"
                      "Uid=austin;"
                      "Pwd=Test;")
                      #"Trusted_Connection=yes;")
cursor = cnxn.cursor()

sql = (
    'INSERT INTO [MES_af].[dbo].[IonTrim] ('
    '[fk_wafer]'
    ',[run]'
    ',[a]'
    ',[b]'
    ',[c]'
    ',[m]'
    ',[n]'
    ',[rsqd]'
    ',[created]'
    ',[updated])'
    'VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)')
values = (7869, 2, 1.5, 0.5, 2, None, None, None, datetime.now(timezone('US/Pacific')), None)
cursor.execute(sql, values)
cnxn.commit()

In [ ]:
import pyodbc 
import pandas as pd
from datetime import datetime
from pytz import timezone


cnxn = pyodbc.connect("Driver={ODBC Driver 17 for SQL Server};"
                      "Server=rdm0sql01;"
                      "Database=MES_af;"
                      "Uid=austin;"
                      "Pwd=Test;")
                      #"Trusted_Connection=yes;")
cursor = cnxn.cursor()

sql = (
    'UPDATE [MES_af].[dbo].[IonTrim] ' 
    'SET '
    '[m] = ?, '
    '[n] = ?, '
    '[rsqd] = ?, '
    '[updated] = ? '
    'WHERE '
    '[fk_wafer] = ? AND'
    '[run] = ?')
values = (0.5, 12, 33, datetime.now(timezone('US/Pacific')), 9999, 2,)
cursor.execute(sql, values)
cnxn.commit()